[2025-01-12T18:20:55.691+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.echo_path manual__2025-01-12T18:20:53.811577+00:00 [queued]>
[2025-01-12T18:20:55.698+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.echo_path manual__2025-01-12T18:20:53.811577+00:00 [queued]>
[2025-01-12T18:20:55.699+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T18:20:55.699+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-01-12T18:20:55.699+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T18:20:55.715+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): echo_path> on 2025-01-12 18:20:53.811577+00:00
[2025-01-12T18:20:55.725+0000] {standard_task_runner.py:52} INFO - Started process 276 to run task
[2025-01-12T18:20:55.729+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coin_scrapper2', 'echo_path', 'manual__2025-01-12T18:20:53.811577+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/AirflowCrypto2.py', '--cfg-path', '/tmp/tmp5b3uqp2o', '--error-file', '/tmp/tmpedczbxqk']
[2025-01-12T18:20:55.731+0000] {standard_task_runner.py:80} INFO - Job 35: Subtask echo_path
[2025-01-12T18:20:55.778+0000] {task_command.py:371} INFO - Running <TaskInstance: coin_scrapper2.echo_path manual__2025-01-12T18:20:53.811577+00:00 [running]> on host a71d0af9bc73
[2025-01-12T18:20:55.870+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=terry
AIRFLOW_CTX_DAG_ID=coin_scrapper2
AIRFLOW_CTX_TASK_ID=echo_path
AIRFLOW_CTX_EXECUTION_DATE=2025-01-12T18:20:53.811577+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-12T18:20:53.811577+00:00
[2025-01-12T18:20:55.871+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-12T18:20:55.872+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python -c "from pyspark.sql import SparkSession; spark = SparkSession.builder.getOrCreate()"']
[2025-01-12T18:20:55.879+0000] {subprocess.py:85} INFO - Output:
[2025-01-12T18:20:56.136+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-01-12T18:20:56.137+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2025-01-12T18:20:56.202+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-12T18:20:56.202+0000] {subprocess.py:92} INFO -   File "<string>", line 1, in <module>
[2025-01-12T18:20:56.203+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-01-12T18:20:56.203+0000] {subprocess.py:92} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-01-12T18:20:56.203+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-01-12T18:20:56.203+0000] {subprocess.py:92} INFO -     SparkContext(conf=conf or SparkConf())
[2025-01-12T18:20:56.203+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 144, in __init__
[2025-01-12T18:20:56.203+0000] {subprocess.py:92} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-01-12T18:20:56.203+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-01-12T18:20:56.204+0000] {subprocess.py:92} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-01-12T18:20:56.204+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-01-12T18:20:56.204+0000] {subprocess.py:92} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-01-12T18:20:56.204+0000] {subprocess.py:92} INFO - Exception: Java gateway process exited before sending its port number
[2025-01-12T18:20:56.223+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-12T18:20:56.258+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-12T18:20:56.265+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=coin_scrapper2, task_id=echo_path, execution_date=20250112T182053, start_date=20250112T182055, end_date=20250112T182056
[2025-01-12T18:20:56.303+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 35 for task echo_path (Bash command failed. The command returned a non-zero exit code 1.; 276)
[2025-01-12T18:20:56.323+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-12T18:20:56.363+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
